title: "DataScience4G"
description: "Data Science for General Audiences"

#baseurl:  http://localhost:4000
baseurl: http://datascience4g.github.io
shiny_url: http://35.182.111.67:3838

include: [".htaccess"]
exclude: ["README.md","LICENSE.md"]
timezone:    America/Edmonton

encoding: UTF-8
markdown: kramdown
kramdown:
  input:          GFM
  hard_wrap:      false
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Bootswatch theme (cosmo)
bswtheme: yeti
# fancy fonts on/off
fancyfonts: true
# navbar style: inverse, transparent
navbar: inverse

disqus:
ads: false

author: '<a href="http://datascience4g.github.io">DataScience4G</a>'
author_plain: 'DataScience4G'

categories: ["apps", "posts"]

gems:
  - jekyll-feed
  - jekyll-sitemap

team:
  - xyz1:
    - name: 'Name 1'
    - pic: 'pic.jpg'
    - link: '#'
    - bio: 'Bio comes here.'
  - xyz2:
    - name: 'Name 2'
    - pic: 'pic.jpg'
    - link: '#'
    - bio: 'Bio comes here.'
  - xyz3:
    - name: 'Name 3'
    - pic: 'pic.jpg'
    - link: '#'
    - bio: 'Bio comes here.'
